// Static list of motif files in public/motifs
export const motifFiles = [
  'Bird1.png',
  'Bird2.png',
  'Crab.png',
  'Flower1.png',
  'Flower2.png',
  'Flower3.png',
  'Flower4.png',
  'Flower5.png',
  'Flower6.png',
  'Glasses.png',
  'Leaf.png',
  'Moon.png',
  'Rings.png',
  'Seahorse.png',
  'Shell2.png',
  'Shell3.png',
  'Shell5.png',
  'Shell6.png',
  'Star.png',
  'Sykkel.png',
  'hang-loose.png',
  'lotus.png',
  'shell1.png',
  'shell4.png',
  'sunset.png',
]
