// Static list of motif files in public/motifs
export const motifFiles = [
  'Bird.png',
  'Bird2.png',
  'Bird6.png',
  'Bug.png',
  'Flower1.png',
  'Flower3.png',
  'Flower4.png',
  'Flower5.png',
  'Flower7.png',
  'Flower8.png',
  'Glasses.png',
  'hang-loose.png',
  'Ladybug.png',
  'Leaf.png',
  'Moon.png',
  'Rings.png',
  'Sea Crab.png',
  'Seahorse.png',
  'shell1.png',
  'shell4.png',
  'Shell5.png',
  'Smile.png',
  'Star.png',
  'Sunflower.png',
  'Sunflower2.png',
  'sunset.png',
  'Sykkel.png',
  'Tuliop flower.png',
]
